---
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
spec:
  containers:
    - name: nginx-container
      image: nginx:1.14.2
      ports:
        - containerPort: 80
      env:
        - name: SECRET_KEY
          value: "sdfh395asfln340"
    - name: sidecar-container
      image: vulnerable-image:latest
      ports:
        - containerPort: 8080
      securityContext:
        runAsUser: 0 # Running container as root
