apiVersion: v1
kind: Pod
metadata:
 name: myapp-pod
 labels:
   app: myapp
spec:
 containers:
   - name: nginx-container
     image: nginx:1.14.2
     ports:
       - containerPort: 80
     env:
     - name: ENV_VAR
       value: "value"
