version: 2.1

executors:
  terraform-executor:
    docker:
      - image: hashicorp/terraform:latest
    working_directory: ~/project

jobs:
  lint:
    docker:
      - image: cytopia/yamllint:latest
    steps:
      - checkout
      - run:
          name: Run yamllint
          command: yamllint .

  checkov:
    docker:
      - image: bridgecrew/checkov:latest
    steps:
      - checkout
      - run:
          name: Run Checkov
          command: checkov -d .

  gitleaks:
    docker:
      - image: zricethezav/gitleaks:latest
    steps:
      - checkout
      - run:
          name: Run Gitleaks
          command: gitleaks detect --source .

  terraform-init:
    executor: terraform-executor
    steps:
      - checkout
      - run:
          name: Terraform Init
          command: terraform init

  terraform-apply:
    executor: terraform-executor
    steps:
      - checkout
      - run:
          name: Terraform Apply
          command: terraform apply -auto-approve

workflows:
  version: 2
  deploy:
    jobs:
      - lint
      - checkov
      - gitleaks
      - terraform-init:
          requires:
            - lint
            - checkov
            - gitleaks
      - terraform-apply:
          requires:
            - terraform-init
